app/category/models.py
from flask.ext.sqlalchemy import SQLAlchemy
from app import db
class category(db.Model):
    __tablename__ = 'category'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    position = db.Column(db.Integer)
    category_id = db.Column(db.Integer)
    def __init__(self, name, position, category_id):
        self.name = name
        self.position = position
        self.category_id = category_id

app/category/forms.py
from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField,validators,SubmitField
class CategoryForm(FlaskForm):
    name=TextField('Name',[validators.Required('Please enter your name'),validators.Length(max=10,message='name is at most 30 characters.')])
    category_id=TextField('category_id')
    postion=TextField('position')

app/category/controllers.py
from app import db
from flask import Blueprint,render_template,url_for,flash,redirect,request,session
from app.category.models import category
from app.category.forms import CategoryForm
import logging
model_category = Blueprint('category', __name__, url_prefix='/category')
@model_category.route('/add/',methods=['GET', 'POST'])
def add():
    form = CategoryForm()
    if request.method == 'POST':
        if not form.validate():
            return render_template('category/index.html',form=form)
        else:
            newcategory = category(form.name.data, form.category_id.data, form.postion.data)
            db.session.add(newcategory)
            db.session.commit()
            return redirect(url_for('category.index'))
    elif request.method == 'GET':
        return render_template('category/add.html', form=form,infos=category.query.all())

@model_category.route('/')
def index():
    return render_template('category/index.html',listcategorys=category.query.all())

app/templates/category/add.html
 <div class="x_panel">
                  <div class="x_title">
                    <h2>Add new Admin</h2>

                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <br />
                    <form id="demo-form2" role="form" action="{{url_for('category.add')}}" method="post" data-parsley-validate class="form-horizontal form-label-left">
                       {{ form.csrf_token }}
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Name<span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <input type="text" name="name" id="first-name" placeholder="Name" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Danh muc</label>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                          <select class="form-control" name="category_id">
                            <option value="0">Danh muc cha</option>
                            {% for info in infos %}
                              <option value="1">{{info.name}}</option>
                            {% endfor%}
                          </select>
                        </div>
                      </div>
                        <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" >Position<span class="required"></span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <input type="number" dirname="email" name="position" placeholder="Position" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                      </div>

                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">

                          <button type="submit" name="submit" class="btn btn-success">Submit</button>
                        </div>
                      </div>

                    </form>
                  </div>
                </div>